### ISSUE TITLE
Segmentation Fault error

### ISSUE THREAD

**Issue by ddurai** [bcgsc/Trans-NanoSim#1]
Hi,
I am very interested in using the code for simulating RNA oxford nanopore reads. But when I run the code I always encounter a segmentation fault. I am using a system with all the required softwares and libraries installed and a python whose version is 3.6.1. Can you please help me in fixing this issue

Thanks

regards
Dilip

**Comment by cheny19** [comment]
Hi Dilip,

Could you provide the log file including the error you encountered? If possible, please also point me the input files you used when the seg fault occured. So I can try to figure out that's causing the error and debug.

Thanks,
Chen

**Comment by saberhq** [comment]
Hi @ddurai Would you please copy paste the error so that I can see where it happens?

**Comment by ddurai** [comment]
Dear @SaberHQ and @cheny19 
Thank you for your reply and I apologise for the delay in responding. I do not get any log file. All I get is a segmentation fault within 2 minutes of my execution. Here is the command I am using:

python read_analysis.py /input/K562.fq -rg hg38.fa -rt Homo_sapiens.GRCh38.cdna.all.fa -annot Homo_sapiens.GRCh38.93.gtf

Unfortunately, I will not be able to provide you with the original fastq file I have as it is currently unpublised. I have attached the screenshot of my execution with this msg

Regards
Dilip
[ScreenTransNanoSim.pdf](https://github.com/bcgsc/Trans-NanoSim/files/2615767/ScreenTransNanoSim.pdf)

**Comment by saberhq** [comment]
Dear @ddurai 

I was actually working on incorporating this pipeline within the [NanoSim](https://github.com/bcgsc/NanoSim) repo. The work is done and you may now use it to simulate both genomic and transcriptomic reads! This repo is now deprecated.

I do believe that Segmentation Fault is something related to your own workstation's memory. Please try our new pipeline in a new computer and see if it solves the issue. I am closing the issue, you may use NanoSim pipeline now as this repo is deprecated.
