### ISSUE TITLE
Error when running model_intron_retention.py

### ISSUE THREAD

**Issue by JoannaTan** [bcgsc/Trans-NanoSim#2]
Hi, 

I am interested to use the codes to simulate RNA data from nanopore.
However, when I ran the code, I encountered the following error:

Traceback (most recent call last):
  File "read_analysis.py", line 301, in <module>
    main()
  File "read_analysis.py", line 289, in main
    model_ir.intron_retention(outfile, ref_t)
  File "model_intron_retention.py", line 41, in intron_retention
    features[feature.iv] += feature_id
UnboundLocalError: local variable 'feature_id' referenced before assignment

Can you help in fixing the issue?

Thank you very much.

**Comment by saberhq** [comment]
Hi @JoannaTan . Thanks for bringing up this issue. First of all, I would like to say that I made several updates to the codes in the past couple of days. Make sure to use the latest codes.

Back to your issue, basically what _model_intron_retention.py_ does is that it gets the reference transcriptome and also reads the transcriptome and genome alignment files along with the GFF file which has been created before and then detects and models the Intron Retention events. 

 The error you are reporting is at the "Reading intron coordinates from GFF file" section. I use HTSeq.GFFReader for this task. Would you mind to give me the GFF file you used? So I can run that part of the code to see whether anything is wrong with it or not? Did you download your GFF file from ensembl? 

Thanks,
Saber.

**Comment by JoannaTan** [comment]
Hi @SaberHQ,

Thank you for your reply.

I downloaded the GTF file from gencode then I converted it myself using the following 
`gt gtf_to_gff3 -tidy -o hg38_annotation.gff3 hg38_annotation.gtf`

I tried to pass the GTF file to Trans-nanosim, but it will always get stuck at the step whereby it converts GTF to GFF3. 

I have attached the GFF file here

[NanoSim_directRNA_training_addedintron.zip](https://github.com/bcgsc/Trans-NanoSim/files/2597541/NanoSim_directRNA_training_addedintron.zip)
