### ISSUE TITLE
Example data for training trans-nanosim for simulating direct RNA sequencing from DNA sequence

### ISSUE THREAD

**Issue by pluralise** [bcgsc/Trans-NanoSim#3]
Hi,
I will do some direct RNA sequencing soon & am trying to simulate the result in advance using trans-nanosim. I plan to use the data from [this article](https://www.nature.com/articles/nmeth.4577) for the characterisation step. I just wanted to check that this data will be okay for training considering the RNA sequencing reads I will collect are from a different organism? I imagine that provided I use the same direct RNA seq kit then the simulation should be appropriate?
Thank you,
Matt

**Comment by saberhq** [comment]
Hi Matt, 

Sorry for replying a bit late. There are very limited direct RNA reads available and I believe that data from the paper you just mentioned is our only chance in here. Obviously, it would be better to train on data from the same organism. However, I think that you can rely on results trained on that dataset for now. I tested Trans-NanoSim using that data as well.

Best,
Saber.

**Comment by pluralise** [comment]
Hi Saber, 
Thank you, I have tried to use trans-nanosim with the yeast data from the article I mentioned but have run into a bunch of errors at the characterisation stage.
It would be great if you could share the output files from the characterisation stage (you mentioned you'd tested trans-nanosim on the data from that article already). That way I can press on to simulating rna-seq of my sequences of interest. Is this something you're able to do?
Thanks,
Matt

**Comment by saberhq** [comment]
Dear @pluralise 

I was actually working on incorporating this pipeline within the [NanoSim](https://github.com/bcgsc/NanoSim) repo. The work is done and you may now use it to simulate both genomic and transcriptomic reads! This repo is now deprecated.

Please try to run it and let me know if you have any questions.
