### ISSUE TITLE
Genome tools dependency

### ISSUE THREAD

**Issue by f0t1h** [bcgsc/Trans-NanoSim#6]
Genome tools is used internally. But, I cannot see it in the README as a dependency. 

`call("gt gtf_to_gff3 -tidy -o " + outfile + ".gff3" + annot, shell=True)`

http://genometools.org/

**Comment by saberhq** [comment]
Thanks for pointing out to this important thing. I will add it as a dependency. By the way, note that we are merging this tool into original [NanoSim](https://github.com/bcgsc/NanoSim) and they will be one standalone pipeline. I will announce it shortly.
