### ISSUE TITLE
GTF path problem

### ISSUE THREAD

**Issue by f0t1h** [bcgsc/Trans-NanoSim#7]
There is a problem with the path computation for gtf files. I get following error.

> fopen(): cannot open file '[experiment-name].gff3/path/to/gtf.gtf': No such file or directory

Caused by:
https://github.com/bcgsc/Trans-NanoSim/blob/5bf5adbc0af320d0fe68d8797e5057c55814535b/src/read_analysis.py#L177-L180

**Comment by daniellezhang** [comment]
the command misses a space after .gff3
so rather than `outfile.gff3 annot`
the command became `outfile.gff3annot`

**Comment by saberhq** [comment]
Thanks @CharlesTaylor and @daniellezhang for spotting this. I made the change now. Please be adviced that I will merge this GitHub repo with the original [NanoSim](https://github.com/bcgsc/NanoSim) pipeline shortly. I tried to include more features. I will release it shortly. and I will inform you guys about that.
