### ISSUE TITLE
gt gff3 stalls at read_analysis.py

### ISSUE THREAD

**Issue by f0t1h** [bcgsc/Trans-NanoSim#8]
Software stops at this line. It was waiting input from the stdin. 
https://github.com/bcgsc/Trans-NanoSim/blob/5bf5adbc0af320d0fe68d8797e5057c55814535b/src/read_analysis.py#L183

**Comment by saberhq** [comment]
@CharlesTaylor did you managed to make it run? This line basically calls and runs the genometools command and the remaining part of the code continues after this step is done. Maybe it is related to genometools dependency. Do you have it installed?

**Comment by saberhq** [comment]
Dear @CharlesTaylor 

I was actually working on incorporating this pipeline within the [NanoSim](https://github.com/bcgsc/NanoSim) repo. The work is done and you may now use it to simulate both genomic and transcriptomic reads! This repo is now deprecated.

I am closing the issue, you may use NanoSim pipeline now as this repo is deprecated.
