### ISSUE TITLE
repo has no license

### ISSUE THREAD

**Issue by daniellezhang** [bcgsc/Trans-NanoSim#9]
Hi There!

I want to modify the codes and the fact that this repo has no license so far kind of worries me.  Would be nice to include a license that allow use and modification of the codes :)

https://choosealicense.com/no-permission/

**Comment by lfaller-zymergen** [comment]
That would be very useful -- +1 on this!

**Comment by saberhq** [comment]
Thanks for bringing this up. I was actually working on incorporating this pipeline within the [NanoSim](https://github.com/bcgsc/NanoSim) repo. Now it is done and you may use it to simulate both genomic and transcriptomic reads! This repo is now deprecated.
